### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by hadron13** [deltanedas/routorio-old#16] opened 2020-12-07 20:49 UTC
trying to control routergeist

```
Mindustry has crashed. How unfortunate.
Version: release build 120
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
3 Mods: dev-mode:2.3.2, ldb:1.1.0, routorio:2.35.8

rhino.EcmaError: TypeError: Cannot call property aimX in object BlockUnitUnit#11929. It is not a function, it is "number". (routergeist#12)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3955)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3935)
	at rhino.ScriptRuntime.typeError(ScriptRuntime.java:3964)
	at rhino.ScriptRuntime.typeError3(ScriptRuntime.java:3986)
	at rhino.ScriptRuntime.notFunctionError(ScriptRuntime.java:4046)
	at rhino.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2350)
	at rhino.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2333)
	at rhino.optimizer.OptRuntime.callProp0(OptRuntime.java:69)
	at rhino.gen.routergeist_33._c_anonymous_3(routergeist:12)
	at rhino.gen.routergeist_33.call(routergeist)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:346)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3303)
	at rhino.gen.routergeist_33.call(routergeist)
	at rhino.JavaAdapter.doCall(JavaAdapter.java:572)
	at rhino.JavaAdapter.callMethod(JavaAdapter.java:554)
	at adapter33.getTileTarget(<adapter>)
	at mindustry.world.blocks.distribution.Router$RouterBuild.updateTile(Router.java:59)
	at mindustry.gen.Building.update(Building.java:1092)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:68)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:58)
	at mindustry.gen.Groups.update(Groups.java:71)
	at mindustry.core.Logic.update(Logic.java:359)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:153)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
```

attacking with routerpede
```
Mindustry has crashed. How unfortunate.
Version: release build 120
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
3 Mods: dev-mode:2.3.2, ldb:1.1.0, routorio:2.35.8

rhino.EcmaError: TypeError: Cannot call property aimX in object BlockUnitUnit#376. It is not a function, it is "number". (routergeist#12)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3955)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3935)
	at rhino.ScriptRuntime.typeError(ScriptRuntime.java:3964)
	at rhino.ScriptRuntime.typeError3(ScriptRuntime.java:3986)
	at rhino.ScriptRuntime.notFunctionError(ScriptRuntime.java:4046)
	at rhino.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2350)
	at rhino.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2333)
	at rhino.optimizer.OptRuntime.callProp0(OptRuntime.java:69)
	at rhino.gen.routergeist_33._c_anonymous_3(routergeist:12)
	at rhino.gen.routergeist_33.call(routergeist)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:346)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3303)
	at rhino.gen.routergeist_33.call(routergeist)
	at rhino.JavaAdapter.doCall(JavaAdapter.java:572)
	at rhino.JavaAdapter.callMethod(JavaAdapter.java:554)
	at adapter30.getTileTarget(<adapter>)
	at mindustry.world.blocks.distribution.Router$RouterBuild.updateTile(Router.java:59)
	at mindustry.gen.Building.update(Building.java:1092)
	at mindustry.entities.EntityGroup.each(EntityGroup.java:68)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:58)
	at mindustry.gen.Groups.update(Groups.java:71)
	at mindustry.core.Logic.update(Logic.java:359)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:153)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:43)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

```

**Comment by deltanedas** [comment] 2020-12-08 17:55
1. ill just remove routergeist, anuke merged router to master a while ago
2. thats a duplicate of the first one

**Closed as completed by deltanedas** 2020-12-08 17:55 UTC
